### ISSUE TITLE
Typo on "Health exams in Vietnam"

### ISSUE THREAD

**Issue by ethan-pawl** [cmustatistics/data-repository#3]
This is a small issue, but the "Variable Descriptions" for the columns `RecExam` and `RecPerExam` say that missing values are denoted as "unknown", but they are actually denoted as "unknow" (missing 'n' at the end).

**Comment by capnrefsmmat** [comment]
That's amusing. Good catch. Would you like to make a pull request? You should just have to edit one line in `medicine/vietnam-health.qmd`:

https://github.com/cmustatistics/data-repository/blob/f6dcb8123e51017df2162816af02398ba83bae63/medicine/vietnam-health.qmd#L64-L65

Probably can do it through the GitHub web interface, since it's such a small tweak.

**Comment by ethan-pawl** [comment]
#4
